### ISSUE TITLE
Future of this integration

### ISSUE THREAD

**Issue by digitalcraig** [adt-pulse-mqtt/adt-pulse-mqtt#30]
I'm switching away from ADT to another alarm company which has native support for Home Assistant, but I will continue to support this integration as long as I'm able. I'm also willing to transfer ownership of this repo, take on contributors, and of course accept pull requests.

To support future breakfix as ADT changes their website, I need to develop tests which can be used with page code contributed by myself and others without relying on a login to the ADT Portal.  This is a top priority before I cancel monitoring service.

**Comment by digitalcraig** [comment]
I have implemented initial support into the tests branch for automated tests using mocha, chai, and nock which have no dependency on the ADT Pulse portal. Along with that, I've added support for Travis CI and Coveralls.io coverage reports. I'm continuing to add tests.

**Comment by digitalcraig** [comment]
## Completed

* Tests branch has been merged into 2.3.1 branch and [pushed to Docker Hub](https://hub.docker.com/r/digitalcraig/adt-pulse-mqtt/tags?page=1&ordering=last_updated&name=2.3.1) for testing.
* New [Github organization](https://github.com/adt-pulse-mqtt) created as future home which should deprecate other forks and repositories. Contributors welcome to the join the new organization.
* New [Docker organization](https://hub.docker.com/u/adtpulsemqtt) created as future home for Docker images.

## To Do
* [ ] New Home Assistant add-on repository which lives under new Github organization and pulls images from new Docker Hub organization
* [ ] Complete testing 2.3.1 for release
* [ ] Update all links and references in README for new organizations
* [ ] Release 2.3.1
* [ ] Transfer repository to new Github organization
* [ ] Configure Docker Hub automated build rules 
* [ ] Archive existing add-on repository
* [ ] Recommend forks archive and point to new organization
* [ ] Post new add-on repository to Home Assistant thread

**Comment by haruny** [comment]
I'll be defunct-ing my repo in favor of this one. I don't think we need the split going forward.

**Comment by digitalcraig** [comment]
Sounds good. I'm finally getting around to implementing what we discussed previously. This repo and the add-on repository will be transferred to a new organization. I'm hoping we can get the word out to our collective install base to move over to the new add-on repository which will pull pre-built images rather than building them locally.

I hope this move will make sure the integration has a future long after I/we are no longer ADT customers. Even if there are no other contributors, I can test changes without access to Pulse portal.

**Comment by digitalcraig** [comment]
The migration is complete. If you are using my original add-on repo, it was transferred to the new organization so the change should be seamless. You may need to "reload" repositories in Home Assistant Supervisor for the new name to show up. If you are using another add-on repository, you should remove it and add https://github.com/adt-pulse-mqtt/hassio to see the new version, v2.3.3.

Once done, the add-on images will be pulled from the new Docker Organization at [adtpulsemqtt/adt-pulse-mqtt-{arch}](https://hub.docker.com/u/adtpulsemqtt). They are no longer locally built.

**Comment by robkjr** [comment]
Ok so I was using the haruny distro for this.  To "migrate" over all I should have to do is add the repo  https://github.com/adt-pulse-mqtt/hassio and then uninstall the haruny one and install the new one? Afte that it all should work normally?

**Comment by digitalcraig** [comment]
Yes, correct. There should be no breaking changes between the two versions.

**Comment by robkjr** [comment]
Even tho I see you aren't using ADT anymore, I'd like to stay on the most current distro.  I notices there was a difference when I clicked on the ADT Pulse MQTT link and it brought me to one that said DEFUNCT.
