### ISSUE TITLE
Motion sensor "devStatOkay" resulting as "active" in SmartThings

### ISSUE THREAD

**Issue by robross0606** [adt-pulse-mqtt/adt-pulse-mqtt#38]
The adt side of things is reporting `devStatOkay` for my motion sensors which should mean "no motion".  However, the bridge is converting this to `active` and reporting that to Smartthings which makes it seems like there is always motion.  I'm using this independently of HASS, so how do I configure this properly?

**Comment by robross0606** [comment]
Looks like it is the same problem as reported [here](https://github.com/adt-pulse-mqtt/adt-pulse-mqtt/issues/28#issuecomment-735484228).  I had assumed this code fix would have been integrated by now and I updated my container.  Seems like the issue [still exists](https://github.com/adt-pulse-mqtt/adt-pulse-mqtt/blob/15c3231a77dec3b16c1a7976d4c04306f08b2f85/adt-pulse-mqtt/server.js#L155)?

**Comment by digitalcraig** [comment]
Sorry, it looks like I dropped the ball on that one since I saw that haruny had replied to the issue.

**Comment by robross0606** [comment]
Resolved by #39
