### ISSUE TITLE
Testers needed - v2.4.0-rc1

### ISSUE THREAD

**Issue by digitalcraig** [adt-pulse-mqtt/adt-pulse-mqtt#40]
I don't expect any issues, but I would like testers for v2.4.0-rc1 before official release.

* Updated mqtt client library to v4.2.6 to resolve several dependency security vulnerabilities
* Updated Dockerfiles to explicitly install Node 14 LTS packages instead of whatever is default in Alpine image
* Updated base Docker images to ones which include the armhf cross-build binaries rather than maintain them directly in this repository

If you are running on Docker on Raspberry Pi (armhf) or Docker on x84/amd64 please pull the Docker images for testing:

* AMD64 - adtpulsemqtt/adt-pulse-mqtt:v.2.4.0-rc
* Raspberry Pi - adtpulsemqtt/adt-pulse-mqtt-armhf:v.2.4.0-rc

**Comment by robross0606** [comment]
I would update to this today and give it a try, but I'm having general issues with the regular version and Smartthings that I need to resolve so I can baseline first.

**Comment by robross0606** [comment]
I can confirm that, after updating to latest Eclipse MQTT instance, I was having problems with "invalid protocol" errors with `latest` (2.3.5) of this project.  However, switching to the 2.4.0 release candidate appears to have solved that problem.  Now if only I could get anything out of MQTT and into Smartthings...

**Comment by digitalcraig** [comment]
What platform are you running on?

**Comment by robross0606** [comment]
Docker Desktop on Windows

**Comment by robross0606** [comment]
Wanted to post here that 2.4.0-rc simply stopped working altogether.  The last time I had a log entry was on 06/27.  Restarting produces zero console feedback and zero topics posted to AMQP.

**Comment by robross0606** [comment]
After restarting several times, I was able to get topics posted sporadically to MQTT but still zero console output on docker.  Very strange.

**Comment by robross0606** [comment]
Switched back to latest (2.3.5) and now I'm getting log messages again, but they're all "Sync stuck?" over and over. 😢

**Comment by robross0606** [comment]
I think Docker Desktop just has networking issues.  It wasn't a clear routing problem this time, but restarting Docker for Desktop unstuck the sync. 🤦

**Comment by digitalcraig** [comment]
Any concerns with pushing this rc to a full release?

**Comment by robross0606** [comment]
I honestly don’t know.  I stopped using it a while ago and never tried again.

**Comment by digitalcraig** [comment]
Is Docker Desktop a testing environment or that where you normally run the add-on?

**Comment by robross0606** [comment]
It is unfortunately where I run things for the time being.

**Comment by digitalcraig** [comment]
v2.4.0-rc2 has been published for a security issue in dependency.
