### ISSUE TITLE
Authentication Failed

### ISSUE THREAD

**Issue by dexsword** [adt-pulse-mqtt/adt-pulse-mqtt#43]
I am getting authentication failures trying to do the initial install/setup. I have the username/pass set in the config. Has something changed?

**Comment by digitalcraig** [comment]
Can you post logs? Do you have two-factor authentication setup on your ADT account?

**Comment by dexsword** [comment]
Sorry I found the issue.

My ADT Pulse login is different from the MyADT login, and even though I changed the password in the config file, ADT blocked my IP from too many invalid attempts.

I had to wait for ADT blacklist to expire and now everything is connecting normally.

**Comment by digitalcraig** [comment]
Awesome, glad to hear you go it resolved.
