### ISSUE TITLE
2-Factor Authentication Readme Update

### ISSUE THREAD

**Issue by JamesValero** [adt-pulse-mqtt/adt-pulse-mqtt#49]
Looks like the 2FA readme needs to be updated. The fork has a much more detailed explanation @ https://github.com/mrjackyliang/homebridge-adt-pulse

For example, the current README here has
Click on the network call (beginning with signin.jsp) appearing in the DevTools window
In the Headers tab, under Form Data, copy the entire fingerprint (after fingerprint:, do not include spaces)
Paste the copied text into the fingerprint field into your config.json

Notice how it says to look for Form Data under the Headers tab instead of the Payload tab (see below). I found that the Payload tab was the right location to find the Form Data.

In the fork, it has
Click on the network call (beginning with signin.jsp?networkid=) appearing in the DevTools window. Select the last one.
In the Payload tab, under Form Data, copy the entire fingerprint (after fingerprint:, do not include spaces)
Paste the copied text into the fingerprint field into your config.json

**Comment by digitalcraig** [comment]
Updated, thanks for submitting.
