### ISSUE TITLE
SmartThings "Edge" drivers

### ISSUE THREAD

**Issue by robross0606** [adt-pulse-mqtt/adt-pulse-mqtt#57]
Any plans for updating the SmartThings integration now that Groovy support is being removed in favor of Lua "Edge" drivers?

**Comment by digitalcraig** [comment]
SmartThings support was developed by @haruny who hasn't been active in project for quite some time. I've never had SmartThings and have to plans to use it. I will accept pull requests.

**Comment by robross0606** [comment]
Okay, that answers the question as a pretty big "no".  I figured as much, but had to ask to be sure.  Thanks!
